version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: jaeger
    ports:
      - "16686:16686" # UI do Jaeger
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      
  postgres:
    image: pgvector/pgvector:pg16
    container_name: pgvector-db
    restart: always
    environment:
      POSTGRES_USER: ezcut
      POSTGRES_PASSWORD: ezcut
      POSTGRES_DB: ezcut
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

